#pragma once

#define TILE_WIDTH 32
#define TILE_HEIGHT 32
#define TILE_FULL_WIDTH 64
#define TILE_FULL_HEIGHT 64

#define MAX_TILE_MAP_WIDTH 3000
#define MAX_TILE_MAP_HEIGHT 3000
#define MIN_TILE_MAP_WIDTH 0
#define MIN_TILE_MAP_HEIGHT 0

#define MAX_MAP_WIDTH (TILE_WIDTH * MAX_TILE_MAP_WIDTH)		// 96000 px
#define MAX_MAP_HEIGHT (TILE_HEIGHT * MAX_TILE_MAP_HEIGHT)	// 96000 px

#define SCREEN_RATIO 0.5625f
#define MAX_SCREEN_WIDTH 2560								// 2560 px
#define MAX_SCREEN_HEIGHT (MAX_SCREEN_WIDTH * SCREEN_RATIO)	// 1440 px
#define MIN_SCREEN_WIDTH 912								// 912 px
#define MIN_SCREEN_HEIGHT (MIN_SCREEN_WIDTH * SCREEN_RATIO)	// 513 px

#define MAX_MUSIC_VOLUME 100.0f
#define MAX_SOUND_VOLUME MAX_MUSIC_VOLUME
#define MIN_MUSIC_VOLUME 0.0f
#define MIN_SOUND_VOLUME MIN_MUSIC_VOLUME
#define START_MUSIC_VOLUME 60.0f
#define START_SOUND_VOLUME 50.0f